### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by superwhiskers** [superwhiskers/whiskerRPG#1]
things i need to do to get this going:

- [ ] clean source folders and remove unneeded deps.
- [ ]  actually get the source paths working
- [ ]  maybe get some motivation to do this *idk*

*well, see this in 10 years when i finally finish this*
